{% set name = "netcdf-java" %}
{% set version = "4.6.21" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://artifacts.unidata.ucar.edu/repository/unidata-releases/edu/ucar/toolsUI/{{ version }}/toolsUI-{{ version }}.jar
  sha256: 7f18897bd10413b19f23aa5dd7f7b8cd4e9a9ccdd3bce840af78023d0a56aa8b

build:
  number: 1
  noarch: generic

requirements:
  run:
    - openjdk >=8

test:
  commands:
    - test -f $PREFIX/bin/ncj4-toolsui            # [unix]
    - if exist %SCRIPT%\ncj4-toolsui.bat exit 1   # [win]
    - ncj4-ncdump
    - ncj4-nccopy
    - ncj4-nccompare
    - ncj4-bufrspliter
    - ncj4-cfpointwriter
    - ncj4-gribcdmindex
    - ncj4-featurescan
#    - ncj4-catalogcrawler

about:
  home: https://www.unidata.ucar.edu/software/netcdf-java/
  summary: The Unidata netcdf-java library. The toolsUI.jar contains everything to run the ToolsUI application directly from it.
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://docs.unidata.ucar.edu/netcdf-java/4.6/userguide/index.html
  dev_url: https://github.com/Unidata/thredds

extra:
  recipe-maintainers:
    - cofinoa
