{% set name = "netcdf-java" %}
{% set version = "5.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.unidata.ucar.edu/{{ name }}/{{ version }}/toolsUI-{{ version }}.jar
  sha256: 003abb36e3f2f9592a80fd8f1f31a91019c7f0519539b4120a651d2f4def63be

build:
  number: 0
  noarch: generic

requirements:
  run:
    - openjdk >=8

test:
  commands:
    - test -f $PREFIX/bin/ncj-toolsui            # [unix]
    - if exist %SCRIPT%\ncj-toolsui.bat exit 1   # [win]
    - ncj-ncdump
    - ncj-nccopy
    - ncj-nccompare
    - ncj-bufrspliter
    - ncj-cfpointwriter
    - ncj-gribcdmindex
    - ncj-featurescan
    - ncj-catalogcrawler

about:
  home: https://www.unidata.ucar.edu/software/netcdf-java/
  summary: The Unidata netcdf-java library. The toolsUI.jar contains everything to run the ToolsUI application directly from it.
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://docs.unidata.ucar.edu/netcdf-java/current/userguide/index.html
  dev_url: https://github.com/unidata/netcdf-java

extra:
  recipe-maintainers:
    - cofinoa
