{% set name = "netcdf-java" %}
{% set version = "5.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://downloads.unidata.ucar.edu/{{ name }}/{{ version }}/toolsUI-{{ version }}.jar
  url: https://github.com/Unidata/netcdf-java/releases/download/v{{ version }}/toolsUI-{{ version }}.jar
  sha256: 3ba80b2b2125028ebcb4d98034b165dfca5a5dddaeaad5fa41ab211aa378fc72

build:
  number: 0
  noarch: generic

requirements:
  build:
    - unix2dos
  run:
    - openjdk >=8

test:
  commands:
    - test -f $PREFIX/bin/ncj-toolsui            # [unix]
    - if exist %SCRIPT%\ncj-toolsui.bat exit 1   # [win]
    - ncj-ncdump
    - ncj-nccopy
    - ncj-nccompare
    - ncj-bufrsplitter
    - ncj-cfpointwriter
    - ncj-gribcdmindex
    - ncj-featurescan
    - ncj-catalogcrawler

about:
  home: https://www.unidata.ucar.edu/software/netcdf-java/
  summary: The Unidata netcdf-java library. The toolsUI.jar contains everything to run the ToolsUI application directly from it.
  license: BSD-3-Clause
  license_file: LICENSE
  license_family: BSD
  doc_url: https://docs.unidata.ucar.edu/netcdf-java/current/userguide/index.html
  dev_url: https://github.com/unidata/netcdf-java

extra:
  recipe-maintainers:
    - cofinoa
